-- mass dummy functions to prevent errors

function spawn_lamp() end
function spawn_small_enemies() end
function spawn_big_enemies() end
function spawn_items() end
function spawn_props() end
function spawn_props2() end
function spawn_props3() end
function spawn_lamp() end
function load_pixel_scene() end
function load_pixel_scene2() end
function spawn_unique_enemy() end
function spawn_unique_enemy2() end
function spawn_unique_enemy3() end
function spawn_ghostlamp() end
function spawn_candles() end
function spawn_potion_altar() end
function spawn_potions() end
function spawn_apparition() end
function spawn_heart() end
function spawn_wands() end
function spawn_portal() end
function spawn_end_portal() end
function spawn_orb() end
function spawn_perk() end
function spawn_all_perks() end
function spawn_wand_trap() end
function spawn_wand_trap_ignite_a() end
function spawn_wand_trap_ignite_b() end
function spawn_wand_trap_electricity_source() end
function spawn_wand_trap_electricity() end
function spawn_moon() end